StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5D5921F55B460917}" {
   Id "EM-DefeatScreenDebriefing"
   Target_en_us "Your entire team has been killed in action."
   Target_fr_fr "Tous vos équipiers ont été tués au combat."
   Target_de_de "Euer gesamtes Team wurde im Einsatz getötet."
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D5921F55B460B54}" {
   Id "EM-DefeatScreenSubtitle"
   Target_en_us "Too many casualties..."
   Target_fr_fr "Trop de victimes..."
   Target_de_de "Zu viele Verluste …"
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D5921F55B460A93}" {
   Id "EM-DefeatScreenTitle"
   Target_en_us "MISSION FAILED"
   Target_fr_fr "ÉCHEC DE LA MISSION"
   Target_de_de "MISSION FEHLGESCHLAGEN"
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D5921F55B460CD0}" {
   Id "EM-DeployMenu_RespawnTickets"
   Target_en_us "Respawn Tickets:"
   Target_fr_fr "Billet de Réapparition:"
   Target_de_de "Respawn-Tickets:"
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D5921F55B460E0B}" {
   Id "EM-ScenarioDesc_Everon"
   Target_en_us "Escape Everon by any means possible."
   Target_fr_fr "Fuyez Everon par tous les moyens."
   Target_de_de "Entkommt Everon um jeden Preis."
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5DC237D501F7959D}" {
   Id "EM-ScenarioExec_Everon"
   Target_en_us "You've got to find a way off this island."\
   ""\
   "Commandeer a boat or helicopter and use it to evacuate. It would be a good idea to search Lamentin's harbour and the airfield. Plan carefully, however. The enemy has a strong presence at each of these locations."\
   ""\
   "Checkpoints and other areas of interest have been marked on your map. They could be viable targets if you need to scavenge supplies."\
   ""\
   "Good luck and stay alive."
   Target_de_de "Ihr müsst einen Weg von dieser Insel finden."\
   ""\
   "Findet ein Boot oder einen Helikopter und entkommt darin. Es wäre eine gute Idee Lamentins Hafen und den Flughafen zu durchsuchen. Plant euer Vorgehen gut, denn der Feind hat an jedem dieser Standorte eine starke Präsenz."\
   ""\
   "Kontrollpunkte und andere wichtige Orte wurden auf eurer Karte markiert. Sie könnten nützliche Ziele für Nachschub sein."\
   ""\
   "Viel Glück und bleibt am Leben!"
   Modified 1573061035
   Author "swellig"
   LastChanged "swellig"
  }
  CustomStringTableItem "{5DC237D993B97819}" {
   Id "EM-ScenarioExec_Title"
   Target_en_us "Execution"
   Target_de_de "Ausführung"
   Modified 1573014708
   Author "swellig"
   LastChanged "swellig"
  }
  CustomStringTableItem "{5DC237D9AECBC7CF}" {
   Id "EM-ScenarioIntro_Title"
   Target_en_us "Introduction"
   Modified 1573014737
   Author "swellig"
   LastChanged "swellig"
  }
  CustomStringTableItem "{5D5921F55B461040}" {
   Id "EM-ScenarioName_Everon"
   Target_en_us "Escape from Everon"
   Target_fr_fr "Fuyez Everon"
   Target_de_de "Entomme aus Everon"
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D5921F55B46127B}" {
   Id "EM-VictoryScreenDebriefing"
   Target_en_us "Against all odds, you managed to escape. Great work!"
   Target_fr_fr "Envers et contre tout, vous avez réussi à vous échapper. Bien joué!"
   Target_de_de "Trotz aller Widrigkeiten habt ihr es geschafft zu entkommen. Großartige Arbeit!"
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D5921F55B461700}" {
   Id "EM-VictoryScreenSubtitle"
   Target_en_us "Escaped"
   Target_fr_fr "Échappé"
   Target_de_de "Entkommen"
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D5921F55B461BA8}" {
   Id "EM-VictoryScreenTitle"
   Target_en_us "MISSION COMPLETED"
   Target_fr_fr "MISSION ACCOMPLIE"
   Target_de_de "MISSION ERFÜLLT"
   Target_cs_cz ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1566136054
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
 }
}